/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Watch for fs events using notify crate which implements native backends and polling feature.
 * This function takes in array of paths to be watched and a callback to be invoked at addon's
 * main thread.
 */
export function watch(
  dirs: string[],
  callback: (err: null | Error, event: string) => void
): JsExternal;
/**
 * This function invokes unwatch method on the specific path and removes that path
 * from watching for fs events.
 */
export function unwatch(ext: JsExternal, dir: string): void;
