/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Initiates recommended watcher instance with threadsafe callback function from
 * node js main thread and call the callback on fs events. This function returns
 * watcher instance which can be used to add paths to be watched for fs events.
 */
export function watch(
  use_poll: boolean,
  callback: (err: null | Error, event: string) => void
): JsExternal;
/** This function takes in watcher instance and a path to be watched for events. */
export function add(ext: JsExternal, dir: string): void;
/**
 * This function invokes unwatch method on the specific path and removes that path
 * from watching for fs events.
 */
export function unwatch(ext: JsExternal, dir: string): void;
