/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function watch(
  dir: string,
  callback: (err: null | Error, event: string) => void
): JsExternal;
export function unwatch(ext: JsExternal, dir: string): void;
